variables:
  COMPOSE_PROJECT_NAME: "jsonapibundle${CI_BUILD_ID}"

stages:
  - test-latest
  - lint
  - test-versions

after_script:
  - cd tests/Resources/docker/
  - echo "Fixing permissions after docker..."
  - bin/php chmod -R 0777 ../../../*
  - docker-compose down
  - echo "All Done!"

# any latest built
ci-latest:
  stage: test-latest
  tags:
      - docker-compose
  script:
    - cd tests/Resources/docker/
    - bin/build.sh
    - bin/setup_fixtures.sh
    - docker-compose run --no-deps --rm php php vendor/bin/phpunit --debug --colors=never --coverage-text=php://stdout --coverage-html=logs/coverage
    - bin/php php ../../../vendor/bin/security-checker security:check ../../../composer.lock

# symfony 4.2 build
ci-symfony4.2:
  stage: test-versions
  tags:
      - docker-compose
  script:
    - cd tests/Resources/docker/
    - docker-compose build
    - docker-compose up -d
    - bin/composer require "symfony/framework-bundle:^4.2" "symfony/form:^4.2" "symfony/validator:^4.2" --no-interaction --no-ansi --prefer-dist
    - docker-compose run --no-deps --rm php composer install --no-interaction --no-ansi --prefer-dist
    - bin/setup_fixtures.sh
    - docker-compose run --no-deps --rm php php vendor/bin/phpunit --debug --colors=never

# symfony 4.1 build
ci-symfony4.1:
  stage: test-versions
  tags:
      - docker-compose
  script:
    - cd tests/Resources/docker/
    - docker-compose build
    - docker-compose up -d
    - bin/composer require "symfony/framework-bundle:^4.1" "symfony/form:^4.1" "symfony/validator:^4.1" --no-interaction --no-ansi --prefer-dist
    - docker-compose run --no-deps --rm php composer install --no-interaction --no-ansi --prefer-dist
    - bin/setup_fixtures.sh
    - docker-compose run --no-deps --rm php php vendor/bin/phpunit --debug --colors=never

# supported 4.0 build
ci-symfony4.0:
  stage: test-versions
  tags:
      - docker-compose
  script:
    - cd tests/Resources/docker/
    - docker-compose build
    - docker-compose up -d
    - bin/composer require "symfony/framework-bundle:^4.0" "symfony/form:^4.0" "symfony/validator:^4.0" --no-interaction --no-ansi --prefer-dist
    - docker-compose run --no-deps --rm php composer install --no-interaction --no-ansi --prefer-dist
    - bin/setup_fixtures.sh
    - docker-compose run --no-deps --rm php php vendor/bin/phpunit --debug --colors=never

# supported 3.4 build
ci-symfony3.4:
  stage: test-versions
  tags:
      - docker-compose
  script:
    - cd tests/Resources/docker/
    - docker-compose build
    - docker-compose up -d
    - mv -f ../app/config/symfony34/config.yml ../app/config/
    - bin/composer require "symfony/framework-bundle:^3.4" "symfony/form:^3.4" "symfony/validator:^3.4" "symfony/config:^3.4" "symfony/translation:^3.4" "symfony/http-foundation:^3.4" "symfony/http-kernel:^3.4" "symfony/twig-bundle:^3.4" --no-interaction --no-ansi --prefer-dist
    - docker-compose run --no-deps --rm php composer install --no-interaction --no-ansi --prefer-dist
    - bin/setup_fixtures.sh
    - docker-compose run --no-deps --rm php php vendor/bin/phpunit --debug --colors=never

# un-supported 3.3 build
ci-symfony3.3:
  stage: test-versions
  tags:
      - docker-compose
  script:
    - cd tests/Resources/docker/
    - docker-compose build
    - docker-compose up -d
    - mv -f ../app/config/symfony34/config.yml ../app/config/
    - bin/composer require "symfony/framework-bundle:^3.3" "symfony/form:^3.3" "symfony/validator:^3.3" "symfony/config:^3.3" "symfony/translation:^3.3" "symfony/http-foundation:^3.3" "symfony/http-kernel:^3.3" "symfony/twig-bundle:^3.3" --no-interaction --no-ansi --prefer-dist
    - docker-compose run --no-deps --rm php composer install --no-interaction --no-ansi --prefer-dist
    - bin/setup_fixtures.sh
    - docker-compose run --no-deps --rm php php vendor/bin/phpunit --debug --colors=never


# un-supported 3.2 build
ci-symfony3.2:
  stage: test-versions
  tags:
      - docker-compose
  script:
    - cd tests/Resources/docker/
    - docker-compose build
    - docker-compose up -d
    - mv -f ../app/config/symfony34/config.yml ../app/config/
    - bin/composer require "symfony/framework-bundle:^3.2" "symfony/form:^3.2" "symfony/validator:^3.2" "symfony/config:^3.2" "symfony/translation:^3.2" "symfony/http-foundation:^3.2" "symfony/http-kernel:^3.2" "symfony/twig-bundle:^3.2" --no-interaction --no-ansi --prefer-dist
    - docker-compose run --no-deps --rm php composer install --no-interaction --no-ansi --prefer-dist
    - bin/setup_fixtures.sh
    - docker-compose run --no-deps --rm php php vendor/bin/phpunit --debug --colors=never


# supported 3.1 build
ci-symfony3.1:
  stage: test-versions
  tags:
      - docker-compose
  script:
    - cd tests/Resources/docker/
    - docker-compose build
    - docker-compose up -d
    - mv -f ../app/config/symfony34/config.yml ../app/config/
    - bin/composer require "symfony/framework-bundle:^3.1" "symfony/form:^3.1" "symfony/validator:^3.1" "symfony/config:^3.1" "symfony/translation:^3.1" "symfony/http-foundation:^3.1" "symfony/http-kernel:^3.1" "symfony/twig-bundle:^3.1" --no-interaction --no-ansi --prefer-dist
    - docker-compose run --no-deps --rm php composer install --no-interaction --no-ansi --prefer-dist
    - bin/setup_fixtures.sh
    - docker-compose run --no-deps --rm php php vendor/bin/phpunit --debug --colors=never

lint:
  stage: lint
  tags:
      - docker-compose
  script:
    - cd tests/Resources/docker/
    - bin/build.sh
    - bin/php_cs --dry-run --using-cache=no
